[[MPIR]]
arch = "aarch64"
git-tree-sha1 = "474f947f27eb6542d65503a63a42e559ca41a240"
os = "macos"

    [[MPIR.download]]
    sha256 = "7e2aa8bd8366f7831bed34b78c720ef2ca6406519240257c77c3b2c9984cc266"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.aarch64-apple-darwin.tar.gz"
[[MPIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a57615b3330e4d11d14e3982efbd710ea9f4b53c"
libc = "glibc"
os = "linux"

    [[MPIR.download]]
    sha256 = "b44f03beb5a51cf0816149ede6da35af37f1d9ba6a2dfe1117ee114f3d1379e5"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.aarch64-linux-gnu-cxx11.tar.gz"
[[MPIR]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3d195116507ae6c709d437e8887c83eca47e382"
libc = "musl"
os = "linux"

    [[MPIR.download]]
    sha256 = "174675ed6c98823012a44584723dc768926fdd3c166aaa105bee07f5f92d502e"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.aarch64-linux-musl-cxx11.tar.gz"
[[MPIR]]
arch = "aarch64"
git-tree-sha1 = "8b4c56f158d4a872147e6241ba087e6248a4d3d9"
os = "freebsd"

    [[MPIR.download]]
    sha256 = "e2d01f8b4d1affc13aa9796c23826ae683506ca70fde79886d06e6fb3d66bd36"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.aarch64-unknown-freebsd.tar.gz"
[[MPIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8497269ad8fb34734ecba28fe754a7743af16b4"
libc = "glibc"
os = "linux"

    [[MPIR.download]]
    sha256 = "fc74b1835dbcc3e3be3f0ff74bca5344a3d57b486042c434a6c98215df92ca8b"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MPIR]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c0285b691233d20a98158be7ca69a1c50cd38a6"
libc = "musl"
os = "linux"

    [[MPIR.download]]
    sha256 = "0f39e2bf3e18e71a4d0d7f6102af392bea1592d56cba988ffe068b37f723da08"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MPIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "701c5253ebadb1640bbdeffbbd735f004b64e161"
libc = "glibc"
os = "linux"

    [[MPIR.download]]
    sha256 = "ecb196dec7cf2e22a5e3b242f6cdda77c821199101bef1a624c6a87d9782eac6"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MPIR]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c14280de4472115ad84d71541dca641761659c3"
libc = "musl"
os = "linux"

    [[MPIR.download]]
    sha256 = "4855676b7c1638709f15e8091ec54c913cbbe21c64d8e8ec9ce0633e3bd3c39d"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MPIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f7b6558cd1245df594b2cfe989354515c486768"
libc = "glibc"
os = "linux"

    [[MPIR.download]]
    sha256 = "06e84585872778a1514aef6ad146334e4e119791fbefc160c7e2363c1473292b"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.i686-linux-gnu-cxx11.tar.gz"
[[MPIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e2e44c69b182eac4c69b579ff7b16ee0c0839f6"
libc = "musl"
os = "linux"

    [[MPIR.download]]
    sha256 = "1e3d8cf8d61337c5919c37cb36ef604eb23764f21e5d63608b62eb1a84b61a23"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.i686-linux-musl-cxx11.tar.gz"
[[MPIR]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "153a981fa451ffb6de540f92c21ba0119a010ef5"
os = "windows"

    [[MPIR.download]]
    sha256 = "44bf375e72d5034646dc59be86055fafd5213e99c5bbd49b778c0952afaa7a88"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.i686-w64-mingw32-cxx11.tar.gz"
[[MPIR]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c86bfdb2f8a242fd76ae20068f1b69e53c120446"
libc = "glibc"
os = "linux"

    [[MPIR.download]]
    sha256 = "d3388d228caf421c5f5b45da6140752b5221d6b8473801e97298dd02f7f4c760"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.riscv64-linux-gnu-cxx11.tar.gz"
[[MPIR]]
arch = "x86_64"
git-tree-sha1 = "0def82a6148b5af0ea83ca39f2534fdd3b0d0119"
os = "macos"

    [[MPIR.download]]
    sha256 = "7c30b3c6372f7665b441e390b74bdafc40f6d122b8f9d85ce27cec883c26d616"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.x86_64-apple-darwin.tar.gz"
[[MPIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "826bf41be944ef8fd0e021c9a191604f28eae028"
libc = "glibc"
os = "linux"

    [[MPIR.download]]
    sha256 = "a550a6ae79487e359b8b4dd6c4e1abc4c8a937f7113ad481c753564d1a536f65"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.x86_64-linux-gnu-cxx11.tar.gz"
[[MPIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1077105414ca1198eb7a8d450d1ce0c8f5cf2624"
libc = "musl"
os = "linux"

    [[MPIR.download]]
    sha256 = "0afc343aa3c4be3c7245a1517a1643a58ea7e39ae7e3fe8c7457a36556319c04"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.x86_64-linux-musl-cxx11.tar.gz"
[[MPIR]]
arch = "x86_64"
git-tree-sha1 = "a5a79d699720572e1d6dfe136a4231a064c7d55d"
os = "freebsd"

    [[MPIR.download]]
    sha256 = "c9f66e78bc93cfc6bf271df7f9386fb1806932daa9c0104b13fc9d7de22a64e7"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.x86_64-unknown-freebsd.tar.gz"
[[MPIR]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59703e379710ebe305399664b4dd69ed54164726"
os = "windows"

    [[MPIR.download]]
    sha256 = "e2d38b273a610c934a9e2bf88ff4242008ce4a92c705d71d3dd54bab22898c31"
    url = "https://github.com/JuliaBinaryWrappers/MPIR_jll.jl/releases/download/MPIR-v3.0.2+1/MPIR.v3.0.2.x86_64-w64-mingw32-cxx11.tar.gz"
