# Autogenerated wrapper script for MPIR_jll for aarch64-apple-darwin
export libmpir

JLLWrappers.@generate_wrapper_header("MPIR")
JLLWrappers.@declare_library_product(libmpir, "@rpath/libmpir.23.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmpir,
        "lib/libmpir.23.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
