# Autogenerated wrapper script for MPIR_jll for armv7l-linux-gnueabihf-cxx03
export libmpir

JLLWrappers.@generate_wrapper_header("MPIR")
JLLWrappers.@declare_library_product(libmpir, "libmpir.so.23")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmpir,
        "lib/libmpir.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
